### ISSUE TITLE
Allow user to replace randomly generated accounts with addresses from a config file

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/create-comit-app#813]
1. Try to find config file in current working directory, i.e. where `comit-scripts` was started
2. If present, read config file and take addresses from there
3. Otherwise, current behaviour

This allows us to have a project-specific comit-scripts config file that contains accounts and can be kept in VCS.

The config file should allow for an arbitrary number of addresses for each blockchain (bitcoin and ethereum).
The ethereum addresses should get both, Ether and ERC20 tokens.
Amounts can stay fixed to what they currently are.

```toml
[bitcoin]
addresses_to_fund = [
	"1GiYYLU6amEX5NnCeS1fuPG5WcVZfRmbiV"
]

[ethereum]
addresses_to_fund = [
	"0x......"
]
```
